apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-koshi
{{- $runtimePort := ternary 15080 8080 (eq .Values.mode "listener") }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $runtimePort }}
      targetPort: {{ $runtimePort }}
      protocol: TCP
  selector:
    app: koshi
